name: CI
on:
  pull_request:
    branches: [ ci ]
  push:
    branches: [ ci ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.1
      - name: Get dependencies
        run: go mod tidy
      - name: Configure dotenv
        run: | #start with mysql
          touch .env
          echo "DB_DRIVER=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASS=root" >> .env
          echo "DB_NAME=go_migrations" >> .env 
      - name: Run tests
        run: |
          go test -v ./tests/...

